version: '3.7'

services:
  api:
    container_name: account-api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3003:3001
      - 9233:9229
    command: npm run start:debug
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb
      - PORT=3001
    networks:
      - account-net
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:3.6.18-xenial
    ports:
      - 27023:27017
    networks:
      - account-net
networks:
  account-net:
