version: '3.7'

services:
  api:
    container_name: ms-account-api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
      - 9233:9229
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb
      - PORT=8080
    networks:
      - account-net
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    ports:
      - 27017:27017
    networks:
      - account-net
networks:
  account-net:
